import { Meta, StoryObj } from '@storybook/react';
import { Checkbox } from '../../components/Atom/Checkbox/Checkbox';
declare const meta: Meta<typeof Checkbox>;
export default meta;
type Story = StoryObj<typeof Checkbox>;
export declare const Standard: Story;
export declare const WithLabel: Story;
export declare const Uncontrolled: Story;
export declare const UncontrolledWithLabel: Story;
export declare const Indeterminate: Story;
export declare const IndeterminateGroup: Story;
