import { Meta, StoryObj } from '@storybook/react';
import { Avatar } from '../../components/Atom/Avatar/Avatar';
declare const meta: Meta<typeof Avatar>;
export default meta;
type Story = StoryObj<typeof Avatar>;
export declare const defaultAvarta: Story;
export declare const InitialAvata: Story;
export declare const ImageAvata: Story;
export declare const IconAvata: Story;
export declare const groupAvata: Story;
