import { Meta, StoryObj } from '@storybook/react';
import { Radio } from '../../components/Atom/Radio/Radio';
declare const meta: Meta<typeof Radio>;
export default meta;
type Story = StoryObj<typeof Radio>;
export declare const Standard: Story;
export declare const WithLabel: Story;
export declare const Uncontrolled: Story;
export declare const UncontrolledWithLabel: Story;
export declare const Disabled: Story;
